root: true
env:
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  project: './tsconfig.json'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars:
    - off
  '@typescript-eslint/no-unused-vars':
    - error
  '@typescript-eslint/no-explicit-any':
    - warn
