version: 2

jobs:
  install:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm --production=false install

      - persist_to_workspace:
          root: ~/
          paths:
            - repo
            - .ssh

  lint:

    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Linting
          command: npm run lint:ts && npm run lint:es

workflows:
  version: 2
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
