name: CI

on:
  push:
  schedule:
    - cron: '30 0 * * *'
  repository_dispatch:
    types:
      - trigger_ci

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm --production=false install
    - run: npm run lint:ts && npm run lint:es
    - run: npm test
